services:
  stockviewer.database:
    image: timescale/timescaledb-ha:pg18
    container_name: stockviewer.database
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - db:/home/postgres/pgdata/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TIMESCALEDB_TELEMETRY: "off"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U tsadmin -d tsdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
  stockviewer.application:
    # production image:
    # image: ghcr.io/finnick4/stockviewer:latest

    # testing / development image:
    image: stockviewer-demo

    container_name: stockviewer.application
    restart: unless-stopped
    depends_on:
      stockviewer.database:
        condition: service_healthy
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - PORT=${PORT}
      - DB_HOST=stockviewer.database
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - HTTPS_MODE=${HTTPS_MODE}
    ports:
      - ${PORT}:${PORT}
volumes:
  db: