services:
  stockviewer.database:
    image: timescale/timescaledb-ha:pg18
    container_name: stockviewer.database
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - db:/home/postgres/pgdata/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TIMESCALEDB_TELEMETRY: "off"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U tsadmin -d tsdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
  stockviewer.application:
    image: stockviewer
    container_name: stockviewer.application
    restart: unless-stopped
    depends_on:
      stockviewer.database:
        condition: service_healthy
    ports:
      - "8000:8000"
volumes:
  db: