function buildAdminStocksPage() {
    const main = `
        <h1>Admin Panel</h1> 
        <p>Lorem ipsum dolor sit amet, dolor sint velit incididunt voluptate nisi et et. Est cupidatat excepteur voluptate. Velit id dolore occaecat ut consectetur. Fugiat ullamco velit pariatur. Ex pariatur exercitation incididunt, incididunt pariatur quis labore nostrud eu. Nisi aliquip sint mollit. Sunt sit minim nisi nisi.
</p><p>Mollit deserunt deserunt proident et. Aliqua laborum occaecat velit sunt. Aliqua magna in commodo ullamco esse. Pariatur adipiscing qui id irure. Tempor laborum magna irure est laborum ex, magna nulla ex consectetur proident reprehenderit consectetur eu. Elit anim eiusmod non commodo nostrud. Officia dolor quis laborum. Anim duis minim nulla commodo adipiscing aliquip est, consectetur quis ex occaecat aliquip anim officia.
</p><p>Aliquip est et quis. Nulla do sed nulla magna reprehenderit labore. Sunt commodo enim dolore, velit ad anim cupidatat commodo ipsum sunt, aute amet non dolor sed officia. Veniam ea elit cillum qui deserunt commodo incididunt, mollit sint ullamco ut eu commodo quis incididunt, eiusmod id elit aute labore enim consequat aute. Aliquip tempor commodo esse adipiscing sint. Minim qui esse ipsum enim aliqua proident nisi. Cillum aliquip ex deserunt culpa nisi veniam ad. Laboris nulla irure elit officia excepteur ut. Proident deserunt occaecat laboris. Amet ipsum in culpa tempor.
</p><p>Amet laborum reprehenderit consectetur eu ut deserunt aliqua, minim ea do id mollit incididunt labore enim, ullamco aliquip minim laboris sit. Aliqua eu tempor nostrud nisi amet velit proident. Pariatur cupidatat lorem occaecat tempor esse nisi. Fugiat ex cillum ut. Anim elit nostrud aliquip ullamco dolor mollit incididunt, voluptate do dolore tempor nostrud tempor ipsum labore, commodo elit pariatur magna. Culpa enim lorem aute tempor reprehenderit ea quis. Pariatur ullamco fugiat sed dolor dolore. Eu sint ad aute enim ex sed. Ea nulla fugiat occaecat dolor lorem reprehenderit sint.
</p><p>Do adipiscing duis aliqua mollit minim irure adipiscing, eiusmod cupidatat cupidatat do ex, eiusmod labore ut minim qui ullamco. Aliqua aliquip quis aliquip nostrud pariatur. Consectetur nisi ullamco eiusmod ea, cupidatat mollit id ex adipiscing cupidatat, sed nisi adipiscing adipiscing. Dolore est culpa magna nostrud, veniam nostrud lorem et veniam nulla, velit officia aliquip laborum occaecat lorem. Cillum irure consequat do ut aliqua.
</p><p>Adipiscing eu reprehenderit dolor labore laborum, adipiscing culpa consectetur dolore. Sit sed ullamco officia et velit aliquip pariatur. Sint voluptate sint ad ex. Dolor irure sed anim sed occaecat. Consequat ullamco nulla do deserunt culpa veniam. Reprehenderit duis nostrud consectetur cupidatat commodo consectetur, do duis incididunt consectetur. Cupidatat in laborum labore sint ullamco enim qui. Ad qui id irure dolore.
</p><p>Ipsum dolore adipiscing non aliquip sunt ut ad. Ullamco aliquip qui consequat velit ut. Consequat ullamco qui et. Lorem incididunt occaecat aliquip veniam ullamco velit. Nulla proident minim exercitation lorem.
</p><p>Esse anim do enim tempor id. Eiusmod eiusmod nisi aliqua enim excepteur tempor. Lorem voluptate consequat sunt. Qui reprehenderit cupidatat id nulla. Non id sunt proident adipiscing sed.
</p><p>Esse lorem occaecat sint aliqua dolore. Sunt aliqua eiusmod cillum sint sit veniam sed. Laboris veniam ut ut pariatur occaecat non sunt. Est commodo sunt do lorem consectetur duis ad, ea quis elit do. Sunt excepteur ad eu excepteur esse. Laboris incididunt eiusmod fugiat labore eu nostrud ipsum. Sunt in labore occaecat cupidatat. Esse excepteur ipsum voluptate ut nostrud aliquip adipiscing. Et incididunt enim consectetur sed consequat excepteur. Irure amet quis sint, tempor labore duis eu voluptate, cillum laborum culpa anim proident reprehenderit do.
</p><p>Mollit deserunt deserunt proident et. Aliqua laborum occaecat velit sunt. Aliqua magna in commodo ullamco esse. Pariatur adipiscing qui id irure. Tempor laborum magna irure est laborum ex, magna nulla ex consectetur proident reprehenderit consectetur eu. Elit anim eiusmod non commodo nostrud. Officia dolor quis laborum. Anim duis minim nulla commodo adipiscing aliquip est, consectetur quis ex occaecat aliquip anim officia.
</p><p>Aliquip est et quis. Nulla do sed nulla magna reprehenderit labore. Sunt commodo enim dolore, velit ad anim cupidatat commodo ipsum sunt, aute amet non dolor sed officia. Veniam ea elit cillum qui deserunt commodo incididunt, mollit sint ullamco ut eu commodo quis incididunt, eiusmod id elit aute labore enim consequat aute. Aliquip tempor commodo esse adipiscing sint. Minim qui esse ipsum enim aliqua proident nisi. Cillum aliquip ex deserunt culpa nisi veniam ad. Laboris nulla irure elit officia excepteur ut. Proident deserunt occaecat laboris. Amet ipsum in culpa tempor.
</p><p>Amet laborum reprehenderit consectetur eu ut deserunt aliqua, minim ea do id mollit incididunt labore enim, ullamco aliquip minim laboris sit. Aliqua eu tempor nostrud nisi amet velit proident. Pariatur cupidatat lorem occaecat tempor esse nisi. Fugiat ex cillum ut. Anim elit nostrud aliquip ullamco dolor mollit incididunt, voluptate do dolore tempor nostrud tempor ipsum labore, commodo elit pariatur magna. Culpa enim lorem aute tempor reprehenderit ea quis. Pariatur ullamco fugiat sed dolor dolore. Eu sint ad aute enim ex sed. Ea nulla fugiat occaecat dolor lorem reprehenderit sint.
</p><p>Do adipiscing duis aliqua mollit minim irure adipiscing, eiusmod cupidatat cupidatat do ex, eiusmod labore ut minim qui ullamco. Aliqua aliquip quis aliquip nostrud pariatur. Consectetur nisi ullamco eiusmod ea, cupidatat mollit id ex adipiscing cupidatat, sed nisi adipiscing adipiscing. Dolore est culpa magna nostrud, veniam nostrud lorem et veniam nulla, velit officia aliquip laborum occaecat lorem. Cillum irure consequat do ut aliqua.
</p><p>Adipiscing eu reprehenderit dolor labore laborum, adipiscing culpa consectetur dolore. Sit sed ullamco officia et velit aliquip pariatur. Sint voluptate sint ad ex. Dolor irure sed anim sed occaecat. Consequat ullamco nulla do deserunt culpa veniam. Reprehenderit duis nostrud consectetur cupidatat commodo consectetur, do duis incididunt consectetur. Cupidatat in laborum labore sint ullamco enim qui. Ad qui id irure dolore.
</p><p>Ipsum dolore adipiscing non aliquip sunt ut ad. Ullamco aliquip qui consequat velit ut. Consequat ullamco qui et. Lorem incididunt occaecat aliquip veniam ullamco velit. Nulla proident minim exercitation lorem.
</p><p>Esse anim do enim tempor id. Eiusmod eiusmod nisi aliqua enim excepteur tempor. Lorem voluptate consequat sunt. Qui reprehenderit cupidatat id nulla. Non id sunt proident adipiscing sed.
</p><p>Esse lorem occaecat sint aliqua dolore. Sunt aliqua eiusmod cillum sint sit veniam sed. Laboris veniam ut ut pariatur occaecat non sunt. Est commodo sunt do lorem consectetur duis ad, ea quis elit do. Sunt excepteur ad eu excepteur esse. Laboris incididunt eiusmod fugiat labore eu nostrud ipsum. Sunt in labore occaecat cupidatat. Esse excepteur ipsum voluptate ut nostrud aliquip adipiscing. Et incididunt enim consectetur sed consequat excepteur. Irure amet quis sint, tempor labore duis eu voluptate, cillum laborum culpa anim proident reprehenderit do.
</p><p>Mollit deserunt deserunt proident et. Aliqua laborum occaecat velit sunt. Aliqua magna in commodo ullamco esse. Pariatur adipiscing qui id irure. Tempor laborum magna irure est laborum ex, magna nulla ex consectetur proident reprehenderit consectetur eu. Elit anim eiusmod non commodo nostrud. Officia dolor quis laborum. Anim duis minim nulla commodo adipiscing aliquip est, consectetur quis ex occaecat aliquip anim officia.
</p><p>Aliquip est et quis. Nulla do sed nulla magna reprehenderit labore. Sunt commodo enim dolore, velit ad anim cupidatat commodo ipsum sunt, aute amet non dolor sed officia. Veniam ea elit cillum qui deserunt commodo incididunt, mollit sint ullamco ut eu commodo quis incididunt, eiusmod id elit aute labore enim consequat aute. Aliquip tempor commodo esse adipiscing sint. Minim qui esse ipsum enim aliqua proident nisi. Cillum aliquip ex deserunt culpa nisi veniam ad. Laboris nulla irure elit officia excepteur ut. Proident deserunt occaecat laboris. Amet ipsum in culpa tempor.
</p><p>Amet laborum reprehenderit consectetur eu ut deserunt aliqua, minim ea do id mollit incididunt labore enim, ullamco aliquip minim laboris sit. Aliqua eu tempor nostrud nisi amet velit proident. Pariatur cupidatat lorem occaecat tempor esse nisi. Fugiat ex cillum ut. Anim elit nostrud aliquip ullamco dolor mollit incididunt, voluptate do dolore tempor nostrud tempor ipsum labore, commodo elit pariatur magna. Culpa enim lorem aute tempor reprehenderit ea quis. Pariatur ullamco fugiat sed dolor dolore. Eu sint ad aute enim ex sed. Ea nulla fugiat occaecat dolor lorem reprehenderit sint.
</p><p>Do adipiscing duis aliqua mollit minim irure adipiscing, eiusmod cupidatat cupidatat do ex, eiusmod labore ut minim qui ullamco. Aliqua aliquip quis aliquip nostrud pariatur. Consectetur nisi ullamco eiusmod ea, cupidatat mollit id ex adipiscing cupidatat, sed nisi adipiscing adipiscing. Dolore est culpa magna nostrud, veniam nostrud lorem et veniam nulla, velit officia aliquip laborum occaecat lorem. Cillum irure consequat do ut aliqua.
</p><p>Adipiscing eu reprehenderit dolor labore laborum, adipiscing culpa consectetur dolore. Sit sed ullamco officia et velit aliquip pariatur. Sint voluptate sint ad ex. Dolor irure sed anim sed occaecat. Consequat ullamco nulla do deserunt culpa veniam. Reprehenderit duis nostrud consectetur cupidatat commodo consectetur, do duis incididunt consectetur. Cupidatat in laborum labore sint ullamco enim qui. Ad qui id irure dolore.
</p><p>Ipsum dolore adipiscing non aliquip sunt ut ad. Ullamco aliquip qui consequat velit ut. Consequat ullamco qui et. Lorem incididunt occaecat aliquip veniam ullamco velit. Nulla proident minim exercitation lorem.
</p><p>Esse anim do enim tempor id. Eiusmod eiusmod nisi aliqua enim excepteur tempor. Lorem voluptate consequat sunt. Qui reprehenderit cupidatat id nulla. Non id sunt proident adipiscing sed.
</p><p>Esse lorem occaecat sint aliqua dolore. Sunt aliqua eiusmod cillum sint sit veniam sed. Laboris veniam ut ut pariatur occaecat non sunt. Est commodo sunt do lorem consectetur duis ad, ea quis elit do. Sunt excepteur ad eu excepteur esse. Laboris incididunt eiusmod fugiat labore eu nostrud ipsum. Sunt in labore occaecat cupidatat. Esse excepteur ipsum voluptate ut nostrud aliquip adipiscing. Et incididunt enim consectetur sed consequat excepteur. Irure amet quis sint, tempor labore duis eu voluptate, cillum laborum culpa anim proident reprehenderit do.
</p><p>Mollit deserunt deserunt proident et. Aliqua laborum occaecat velit sunt. Aliqua magna in commodo ullamco esse. Pariatur adipiscing qui id irure. Tempor laborum magna irure est laborum ex, magna nulla ex consectetur proident reprehenderit consectetur eu. Elit anim eiusmod non commodo nostrud. Officia dolor quis laborum. Anim duis minim nulla commodo adipiscing aliquip est, consectetur quis ex occaecat aliquip anim officia.
</p><p>Aliquip est et quis. Nulla do sed nulla magna reprehenderit labore. Sunt commodo enim dolore, velit ad anim cupidatat commodo ipsum sunt, aute amet non dolor sed officia. Veniam ea elit cillum qui deserunt commodo incididunt, mollit sint ullamco ut eu commodo quis incididunt, eiusmod id elit aute labore enim consequat aute. Aliquip tempor commodo esse adipiscing sint. Minim qui esse ipsum enim aliqua proident nisi. Cillum aliquip ex deserunt culpa nisi veniam ad. Laboris nulla irure elit officia excepteur ut. Proident deserunt occaecat laboris. Amet ipsum in culpa tempor.
</p><p>Amet laborum reprehenderit consectetur eu ut deserunt aliqua, minim ea do id mollit incididunt labore enim, ullamco aliquip minim laboris sit. Aliqua eu tempor nostrud nisi amet velit proident. Pariatur cupidatat lorem occaecat tempor esse nisi. Fugiat ex cillum ut. Anim elit nostrud aliquip ullamco dolor mollit incididunt, voluptate do dolore tempor nostrud tempor ipsum labore, commodo elit pariatur magna. Culpa enim lorem aute tempor reprehenderit ea quis. Pariatur ullamco fugiat sed dolor dolore. Eu sint ad aute enim ex sed. Ea nulla fugiat occaecat dolor lorem reprehenderit sint.
</p><p>Do adipiscing duis aliqua mollit minim irure adipiscing, eiusmod cupidatat cupidatat do ex, eiusmod labore ut minim qui ullamco. Aliqua aliquip quis aliquip nostrud pariatur. Consectetur nisi ullamco eiusmod ea, cupidatat mollit id ex adipiscing cupidatat, sed nisi adipiscing adipiscing. Dolore est culpa magna nostrud, veniam nostrud lorem et veniam nulla, velit officia aliquip laborum occaecat lorem. Cillum irure consequat do ut aliqua.
</p><p>Adipiscing eu reprehenderit dolor labore laborum, adipiscing culpa consectetur dolore. Sit sed ullamco officia et velit aliquip pariatur. Sint voluptate sint ad ex. Dolor irure sed anim sed occaecat. Consequat ullamco nulla do deserunt culpa veniam. Reprehenderit duis nostrud consectetur cupidatat commodo consectetur, do duis incididunt consectetur. Cupidatat in laborum labore sint ullamco enim qui. Ad qui id irure dolore.
</p><p>Ipsum dolore adipiscing non aliquip sunt ut ad. Ullamco aliquip qui consequat velit ut. Consequat ullamco qui et. Lorem incididunt occaecat aliquip veniam ullamco velit. Nulla proident minim exercitation lorem.
</p><p>Esse anim do enim tempor id. Eiusmod eiusmod nisi aliqua enim excepteur tempor. Lorem voluptate consequat sunt. Qui reprehenderit cupidatat id nulla. Non id sunt proident adipiscing sed.
</p><p>Esse lorem occaecat sint aliqua dolore. Sunt aliqua eiusmod cillum sint sit veniam sed. Laboris veniam ut ut pariatur occaecat non sunt. Est commodo sunt do lorem consectetur duis ad, ea quis elit do. Sunt excepteur ad eu excepteur esse. Laboris incididunt eiusmod fugiat labore eu nostrud ipsum. Sunt in labore occaecat cupidatat. Esse excepteur ipsum voluptate ut nostrud aliquip adipiscing. Et incididunt enim consectetur sed consequat excepteur. Irure amet quis sint, tempor labore duis eu voluptate, cillum laborum culpa anim proident reprehenderit do.
</p><p>Mollit deserunt deserunt proident et. Aliqua laborum occaecat velit sunt. Aliqua magna in commodo ullamco esse. Pariatur adipiscing qui id irure. Tempor laborum magna irure est laborum ex, magna nulla ex consectetur proident reprehenderit consectetur eu. Elit anim eiusmod non commodo nostrud. Officia dolor quis laborum. Anim duis minim nulla commodo adipiscing aliquip est, consectetur quis ex occaecat aliquip anim officia.
</p><p>Aliquip est et quis. Nulla do sed nulla magna reprehenderit labore. Sunt commodo enim dolore, velit ad anim cupidatat commodo ipsum sunt, aute amet non dolor sed officia. Veniam ea elit cillum qui deserunt commodo incididunt, mollit sint ullamco ut eu commodo quis incididunt, eiusmod id elit aute labore enim consequat aute. Aliquip tempor commodo esse adipiscing sint. Minim qui esse ipsum enim aliqua proident nisi. Cillum aliquip ex deserunt culpa nisi veniam ad. Laboris nulla irure elit officia excepteur ut. Proident deserunt occaecat laboris. Amet ipsum in culpa tempor.
</p><p>Amet laborum reprehenderit consectetur eu ut deserunt aliqua, minim ea do id mollit incididunt labore enim, ullamco aliquip minim laboris sit. Aliqua eu tempor nostrud nisi amet velit proident. Pariatur cupidatat lorem occaecat tempor esse nisi. Fugiat ex cillum ut. Anim elit nostrud aliquip ullamco dolor mollit incididunt, voluptate do dolore tempor nostrud tempor ipsum labore, commodo elit pariatur magna. Culpa enim lorem aute tempor reprehenderit ea quis. Pariatur ullamco fugiat sed dolor dolore. Eu sint ad aute enim ex sed. Ea nulla fugiat occaecat dolor lorem reprehenderit sint.
</p><p>Do adipiscing duis aliqua mollit minim irure adipiscing, eiusmod cupidatat cupidatat do ex, eiusmod labore ut minim qui ullamco. Aliqua aliquip quis aliquip nostrud pariatur. Consectetur nisi ullamco eiusmod ea, cupidatat mollit id ex adipiscing cupidatat, sed nisi adipiscing adipiscing. Dolore est culpa magna nostrud, veniam nostrud lorem et veniam nulla, velit officia aliquip laborum occaecat lorem. Cillum irure consequat do ut aliqua.
</p><p>Adipiscing eu reprehenderit dolor labore laborum, adipiscing culpa consectetur dolore. Sit sed ullamco officia et velit aliquip pariatur. Sint voluptate sint ad ex. Dolor irure sed anim sed occaecat. Consequat ullamco nulla do deserunt culpa veniam. Reprehenderit duis nostrud consectetur cupidatat commodo consectetur, do duis incididunt consectetur. Cupidatat in laborum labore sint ullamco enim qui. Ad qui id irure dolore.
</p><p>Ipsum dolore adipiscing non aliquip sunt ut ad. Ullamco aliquip qui consequat velit ut. Consequat ullamco qui et. Lorem incididunt occaecat aliquip veniam ullamco velit. Nulla proident minim exercitation lorem.
</p><p>Esse anim do enim tempor id. Eiusmod eiusmod nisi aliqua enim excepteur tempor. Lorem voluptate consequat sunt. Qui reprehenderit cupidatat id nulla. Non id sunt proident adipiscing sed.
</p><p>Esse lorem occaecat sint aliqua dolore. Sunt aliqua eiusmod cillum sint sit veniam sed. Laboris veniam ut ut pariatur occaecat non sunt. Est commodo sunt do lorem consectetur duis ad, ea quis elit do. Sunt excepteur ad eu excepteur esse. Laboris incididunt eiusmod fugiat labore eu nostrud ipsum. Sunt in labore occaecat cupidatat. Esse excepteur ipsum voluptate ut nostrud aliquip adipiscing. Et incididunt enim consectetur sed consequat excepteur. Irure amet quis sint, tempor labore duis eu voluptate, cillum laborum culpa anim proident reprehenderit do.
</p><p>Mollit deserunt deserunt proident et. Aliqua laborum occaecat velit sunt. Aliqua magna in commodo ullamco esse. Pariatur adipiscing qui id irure. Tempor laborum magna irure est laborum ex, magna nulla ex consectetur proident reprehenderit consectetur eu. Elit anim eiusmod non commodo nostrud. Officia dolor quis laborum. Anim duis minim nulla commodo adipiscing aliquip est, consectetur quis ex occaecat aliquip anim officia.
</p><p>Aliquip est et quis. Nulla do sed nulla magna reprehenderit labore. Sunt commodo enim dolore, velit ad anim cupidatat commodo ipsum sunt, aute amet non dolor sed officia. Veniam ea elit cillum qui deserunt commodo incididunt, mollit sint ullamco ut eu commodo quis incididunt, eiusmod id elit aute labore enim consequat aute. Aliquip tempor commodo esse adipiscing sint. Minim qui esse ipsum enim aliqua proident nisi. Cillum aliquip ex deserunt culpa nisi veniam ad. Laboris nulla irure elit officia excepteur ut. Proident deserunt occaecat laboris. Amet ipsum in culpa tempor.
</p><p>Amet laborum reprehenderit consectetur eu ut deserunt aliqua, minim ea do id mollit incididunt labore enim, ullamco aliquip minim laboris sit. Aliqua eu tempor nostrud nisi amet velit proident. Pariatur cupidatat lorem occaecat tempor esse nisi. Fugiat ex cillum ut. Anim elit nostrud aliquip ullamco dolor mollit incididunt, voluptate do dolore tempor nostrud tempor ipsum labore, commodo elit pariatur magna. Culpa enim lorem aute tempor reprehenderit ea quis. Pariatur ullamco fugiat sed dolor dolore. Eu sint ad aute enim ex sed. Ea nulla fugiat occaecat dolor lorem reprehenderit sint.
</p><p>Do adipiscing duis aliqua mollit minim irure adipiscing, eiusmod cupidatat cupidatat do ex, eiusmod labore ut minim qui ullamco. Aliqua aliquip quis aliquip nostrud pariatur. Consectetur nisi ullamco eiusmod ea, cupidatat mollit id ex adipiscing cupidatat, sed nisi adipiscing adipiscing. Dolore est culpa magna nostrud, veniam nostrud lorem et veniam nulla, velit officia aliquip laborum occaecat lorem. Cillum irure consequat do ut aliqua.
</p><p>Adipiscing eu reprehenderit dolor labore laborum, adipiscing culpa consectetur dolore. Sit sed ullamco officia et velit aliquip pariatur. Sint voluptate sint ad ex. Dolor irure sed anim sed occaecat. Consequat ullamco nulla do deserunt culpa veniam. Reprehenderit duis nostrud consectetur cupidatat commodo consectetur, do duis incididunt consectetur. Cupidatat in laborum labore sint ullamco enim qui. Ad qui id irure dolore.
</p><p>Ipsum dolore adipiscing non aliquip sunt ut ad. Ullamco aliquip qui consequat velit ut. Consequat ullamco qui et. Lorem incididunt occaecat aliquip veniam ullamco velit. Nulla proident minim exercitation lorem.
</p><p>Esse anim do enim tempor id. Eiusmod eiusmod nisi aliqua enim excepteur tempor. Lorem voluptate consequat sunt. Qui reprehenderit cupidatat id nulla. Non id sunt proident adipiscing sed.
</p><p>Esse lorem occaecat sint aliqua dolore. Sunt aliqua eiusmod cillum sint sit veniam sed. Laboris veniam ut ut pariatur occaecat non sunt. Est commodo sunt do lorem consectetur duis ad, ea quis elit do. Sunt excepteur ad eu excepteur esse. Laboris incididunt eiusmod fugiat labore eu nostrud ipsum. Sunt in labore occaecat cupidatat. Esse excepteur ipsum voluptate ut nostrud aliquip adipiscing. Et incididunt enim consectetur sed consequat excepteur. Irure amet quis sint, tempor labore duis eu voluptate, cillum laborum culpa anim proident reprehenderit do.
</p><p>Adipiscing exercitation culpa id do laborum deserunt lorem, irure voluptate nulla minim id, excepteur nostrud est dolor. Nulla dolore eu cillum cillum. Est commodo ullamco id id sunt voluptate ex, et adipiscing elit laboris amet incididunt irure. Reprehenderit reprehenderit esse consectetur elit veniam cupidatat. Excepteur aliqua in quis reprehenderit eiusmod aliqua. Dolor ut nisi reprehenderit. Ad non sunt aliqua aute laboris. Amet aute ad ex ipsum ad. Sit excepteur quis laboris consequat voluptate, nostrud esse deserunt officia amet laboris minim. Aliquip do ex deserunt dolor elit anim et.</p>`;
    const side = `<nav class="linklist">
            <a is="a-button" href="/admin/users" class="sidebarElement btn">Users</a>
            <a is="a-button" href="/admin/stocks" class="sidebarElement selected btn">Stocks</a> 
            </nav>`

    setMainBodyHTMLAndSidebar(main, side);
}